export const originList = [{
  id: 1,
  name: 'John',
  nickname: 'H',
  website: 'https://www.google.com',
}, {
  id: 2,
  name: 'Stanney',
  nickname: 'H',
  website: 'https://www.google.com',
}, {
  id: 3,
  name: 'Travor',
  nickname: 'H',
  website: 'https://www.google.com',
}, {
  id: 4,
  name: 'Elephant',
  nickname: 'H',
  website: 'https://www.google.com',
}, {
  id: 5,
  name: 'Banana',
  nickname: 'H',
  website: 'https://www.google.com',
}, {
  id: 6,
  name: 'Orange',
  nickname: 'H',
  website: 'https://www.google.com',
}, {
  id: 7,
  name: 'Young',
  nickname: 'H',
  website: 'https://www.google.com',
}, {
  id: 8,
  name: 'Old',
  nickname: 'H',
  website: 'https://www.google.com',
}, {
  id: 9,
  name: 'Handsome',
  nickname: 'H',
  website: 'https://www.google.com',
}];

export const moreList = [{
  id: 10,
  name: 'Benson',
  nickname: 'H',
  website: 'https://www.google.com',
}, {
  id: 11,
  name: 'Emily',
  nickname: 'H',
  website: 'https://www.google.com',
}, {
  id: 12,
  name: 'Apple',
  nickname: 'H',
  website: 'https://www.google.com',
}];
